config/routes.rb
# encoding: UTF-8
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/20150612', as: 'rails_admin'

  devise_for :users

  root 'welcome#index'

  namespace :welcome do
    get '/' => :index
    get '/demo' => :demo
    get '/map' => :map
    get '/temp' => :temp
    get '/unsigned' => :unsigned
  end

  namespace :open do
    get '/' => :index
    get '/map' => :map
    get '/rank' => :rank
    # temp
    get '/students' => :students
    get '/coaches' => :coaches
    get '/student_sources' => :student_sources
    # for exe
    get '/lakldnfhw' => :lakldnfhw
    get '/mxl82wepoasdm' => :mxl82wepoasdm
    get '/ekz1k4xja1ve5y4r' => :ekz1k4xja1ve5y4r
  end

  namespace :contact_logs do
    get 'new_contact_log' => :new_contact_log
    post 'new_contact_log' => :new_contact_log
  end

  namespace :service do
    post 'assign_task' => :assign_task
    get 'search' => :search
    post 'daily_sign' => :daily_sign
    post 'sms_consultant' => :sms_consultant
  end

  resources :intentions do
    collection do
      post 'get_intention_list' => :get_intention_list
    end
  end

  resources :fees, only: [:index] do
    collection do
      get 'should_pay' => :should_pay
      get 'report' => :report
    end
  end

  resources :pay_units do
    get 'payments' => :payments
    member do
      get 'pay_accounts_select' => :pay_accounts_select
      get 'get_accounts_select' => :get_accounts_select
    end
  end

  resources :payments do
    get 'report_line' => :report_line
  end

  resources :students do
    resources :residence_cards
    resources :contact_logs
    resources :fees do
      resources :payments do
        post 'update_post' => :update_post
        get 'report_edit' => :report_edit
      end
      collection do
        get 'new_exams' => :new_exams
      end
    end
    member do
      post 'update_km1' => :update_km1
      post 'fee_list' => :fee_list
      post 'update_lz' => :update_lz
      post 'has_contact_task' => :has_contact_task
    end
    collection do
      post 'get_student_status' => :get_student_status
      post 'update_id_card' => :update_id_card
      get 'upload_id_card_form' => :upload_id_card_form
      post 'notify_got_number' => :notify_got_number
      post 'notify_got_card' => :notify_got_card
      get 'signed_up' => :signed_up
      get 'wait_pay' => :wait_pay
      get 'need_contact' => :need_contact
      post 'update_evaluation' => :update_evaluation
      post 'peek_before_evaluation' => :peek_before_evaluation
      get 'student_xlsx' => :student_xlsx
      get 'students_process_list' => :students_process_list
    end
  end

  resources :fees do
  end

  resources :student_sources do
    # resources :source_contracts
    resources :source_contacts
    collection do
      get 'list' => :list
      get 'new_source_contact' => :new_source_contact
      post 'new_source_contact' => :new_source_contact
    end
  end

  resources :coaches, only: [:index, :new, :show, :edit, :update, :create] do
    resources :train_services, only: [:index, :new, :show, :edit, :update, :create]
    collection do
      get 'train_services' => :train_services
      post 'train_services' => :train_services
    end
  end

  resources :work_tasks do
    collection do
      post 'process_task' => :process_task
    end
  end

  namespace :api do
    post 'notify' => :notify
  end

  namespace :m do
    root 'dashboard#index'
    namespace :dashboard do
      get '/' => :index
      post '/logout' => :logout
    end
    resources :intentions
    resources :students do
      resources :contact_logs
      member do
        get 'set_to_me' => :set_to_me
      end
      collection do
        post 'query' => :query
      end
    end
  end

end

app/models/contact_log.rb
# encoding: UTF-8
class ContactLog < ActiveRecord::Base
  belongs_to :student
  belongs_to :user

  enum contact_type: [:intent, :trylearn, :sign_up, :suggestion, :complaint, :coaching_business]
  enum current_status: [:wait_call, :contacting, :booking, :wait_pay, :signed_up, :canceled]

  def self.contact_types_for_select
    contact_types.map do |contact_type, _|
      [I18n.t("contact_types.#{contact_type}"), contact_type]
    end
  end

  def self.current_status_for_select
    current_statuses.map do |current_status, _|
      [I18n.t("current_status.#{current_status}"), current_status]
    end
  end

end

app/controllers/contact_logs_controller.rb
# encoding: UTF-8
class ContactLogsController < PcApplicationController
  include SendNotifications
  before_action :authenticate_user!
  load_and_authorize_resource
  def index
  end

  def new_contact_log
    if request.method.downcase == 'post'
      redirect_to new_student_contact_log_path(params[:student_id])
    end
  end

  def new
    @current_page = :new_contact_log_path
    @contact_log = current_user.contact_logs.build
    @student = Student.find(params[:student_id])
  end

  def create
    user_id = current_user.id
    user_id = params[:contact_log][:user_id].to_i if params[:contact_log][:user_id].present?
    user = User.find(user_id)
    contact_log = user.contact_logs.build(new_contact_params)
    student_id = params[:student_id].to_i
    contact_log.student = Student.find(student_id)
    if contact_log.save
      contact_log.student.intention.update(next_contact_at: contact_log.next_contact_at, current_status: contact_log.current_status)

      contact_log.student.update(signed_at: new_contact_params[:created_at]) if new_contact_params[:current_status] == 'signed_up' && contact_log.student.signed_at.nil?
      contact_log.student.update(signed_at: nil) if new_contact_params[:current_status] == 'canceled'

      notify = {
        operator: user.name,
        message: "录入了【#{contact_log.student.name}】学员的一条新联系记录，状态变更为：#{I18n.t("current_status.#{contact_log.current_status}")}"
      }
      send_erp_notify(notify)

      redirect_to intention_path(contact_log.student.intention)
    else
      redirect_to new_contact_log_path(contact_log.student)
    end
  end

  def edit
  end

  def show
  end

  private

  def new_contact_params
    params.require(:contact_log).permit(:contact_type, :current_status, :need_contact, :next_contact_at, :contact_log, :created_at)
  end

  # https://github.com/CanCanCommunity/cancancan/wiki/Strong-Parameters
  def create_params
    params.require(:contact_log).permit(:contact_type, :current_status, :need_contact, :next_contact_at, :contact_log)
  end
end

app/controllers/m/contact_logs_controller.rb
class M::ContactLogsController < MController
  before_action :authenticate_user!
  include SendNotifications

  def index
  end

  def new
    @contact_log = current_user.contact_logs.build
    @student = Student.find(params[:student_id])
  end

  def create
    user_id = current_user.id
    user_id = params[:contact_log][:user_id].to_i if params[:contact_log][:user_id].present?
    user = User.find(user_id)
    contact_log = user.contact_logs.build(new_contact_params)
    student_id = params[:student_id].to_i
    student = Student.find(student_id)
    contact_log.student = student
    if contact_log.save
      student.intention.update(next_contact_at: contact_log.next_contact_at, current_status: contact_log.current_status)

      student.update(signed_at: new_contact_params[:created_at]) if new_contact_params[:current_status] == 'signed_up' && contact_log.student.signed_at.nil?

      notify = {
        operator: user.name,
        message: "录入了【#{contact_log.student.name}】学员的一条新联系记录，状态变更为：#{I18n.t("current_status.#{contact_log.current_status}")}"
      }
      send_erp_notify(notify)

      redirect_to m_student_path(student)
    else
      redirect_to new_m_student_contact_log_path(student)
    end
  end

  def show
  end

  def edit
  end

  private

  def new_contact_params
    params.require(:contact_log).permit(:contact_type, :current_status, :need_contact, :next_contact_at, :contact_log, :created_at)
  end
end

app/controllers/m/dashboard_controller.rb
class M::DashboardController < MController
  before_action :authenticate_user!
  def index
    @tasks = WorkTask.where(to_user_id: current_user.id)
  end

  def logout
    sign_out current_user
    render json: { error_code: '0', error_message: '' }
  end
end

app/controllers/m/intentions_controller.rb
class M::IntentionsController < MController
  before_action :authenticate_user!
  include SendNotifications

  def index
  end

  def new
    @student = current_user.students.build
    @student.build_intention
  end

  def create
    # get user
    user = current_user
    # build student of user
    @student = user.students.build(params_of_student)
    # bind intention user to student.user
    @student.intention.user = @student.user
    # pick student_source_id
    student_source_id = params[:student][:student_source][:id]
    # build default contact log
    contact_log_entity = user.contact_logs.build(default_contact_log)
    @student.contact_logs << contact_log_entity

    if @student.save
      @student.intention.update(next_contact_at: Date.today, current_status: 0)
      # bind student_source for intention
      if student_source_id.is_number?
        student_source = StudentSource.find(student_source_id)
        @student.intention.student_source = student_source
      else
        @student.intention.student_source = nil
      end

      notify = {
        operator: user.name,
        message: "通过手机创建了【#{@student.name}】学员，并录入了他（她）的意向信息"
      }
      send_erp_notify(notify)

      respond_to do |format|
        format.html { redirect_to m_student_path(@student) }
      end
    else
      respond_to do |format|
        format.html { redirect_to :back, alert: @student.errors.messages.values.first.try(&:first) }
      end
    end
  end

  def show
  end

  def edit
  end

  private

  def params_of_student
    params.require(:student).permit(:name, :sex, :phone, :id_card, :address, :unit, intention_attributes: [:source])
  end

  def default_contact_log
    {
      contact_type: 'intent',
      current_status: 'wait_call',
      need_contact: 1,
      next_contact_at: Date.today,
      contact_log: ''
    }
  end
end

app/controllers/m/students_controller.rb
class M::StudentsController < MController
  before_action :authenticate_user!
  before_action :set_student, only: [:show, :edit]
  require 'phone_ext'
  include SendNotifications

  def index
    @intentions = Intention.where.not(current_status: 5).order(updated_at: :desc, next_contact_at: :asc)
    if current_user.has_role? :school_ceo
      @intentions = @intentions.where("user_id = :user_id OR user_id IS NULL", { user_id: current_user.id })
    end
  end

  def show
    @contact_logs = @student.contact_logs.order(updated_at: :desc)
  end

  def edit
  end

  def query
    q = params[:q].to_s
    @intentions = Intention.joins(:student).where("`students`.`phone` LIKE ? OR `students`.`name` LIKE ?", "%#{q}%", "%#{q}%")
    @intentions = @intentions.where.not(current_status: 5).order(updated_at: :desc, next_contact_at: :asc)
    render '_student_list', layout: false
  end

  def set_to_me
    student = Student.find(params[:id])
    student.update(user_id: current_user.id)
    redirect_to m_student_path(student)
  end

  private

  def params_student
    params.require(:student).permit(:phone, :name, :sex, :address, :unit, :id_card, :coach_id, :is_local, :swift_number, :train_service_id, :process)
  end

  def set_student
    @student = Student.find(params[:id])
  end
end

app/controllers/m_controller.rb
class MController < ApplicationController
  layout "m"
end

app/views/m/contact_logs/new.html.erb
<% content_for :title, "新的联系" %>
<style type="text/css">
</style>
<header class="ui-header ui-header-positive ui-border-b">
  <i class="ui-icon-return" onclick="history.back()"></i>
  <h1><%= yield(:title) %></h1>
  <i class="ui-icon-refresh" onclick="refresh()" style="display: block;
    position: absolute;
    right: 10px;
    top: 0;"></i>
</header>
<div class="ui-container">
  <div class="ui-form ui-border-t">
  <%= form_for(@contact_log, url: m_student_contact_logs_path, method: :post, html: { class: "ui form" }) do |f| %>
    <% if current_user.has_role? :can_choose_user %>
    <div class="ui-form-item ui-border-b">
      <%= f.label :user_id, "创建人" %>
      <div class="ui-select">
      <%= f.select :user_id, options_for_select(User.user_for_select, current_user.id), {}, class: "ui dropdown user-id" %>
      </div>
    </div>
    <% end %>

    <div class="ui-form-item ui-border-b">
      <%= f.label :contact_type, "联系类型" %>
      <div class="ui-select">
      <% if @student.contact_logs.count > 0 %>
        <%= f.select :contact_type, options_for_select(ContactLog.contact_types_for_select, @student.contact_logs.last.contact_type) %>
      <% else %>
        <%= f.select :contact_type, options_for_select(ContactLog.contact_types_for_select) %>
      <% end %>
      </div>
    </div>

    <div class="ui-form-item ui-border-b">
      <%= f.label :current_status, "当前状态" %>
      <div class="ui-select">
      <%= f.select :current_status, options_for_select(ContactLog.current_status_for_select, @student.intention.current_status) %>
      </div>
    </div>

    <div class="ui-form-item ui-border-b">
      <%= f.label :created_at, "创建日期" %>
      <%= f.text_field :created_at, { placeholder: '创建日期', type: 'date', value: Date.today.to_s(:db) } %>
      <a href="#" class="ui-icon-close"></a>
    </div>

    <div class="ui-form-item ui-form-item-switch ui-border-b">
      <p>需要联系</p>
      <label class="ui-switch">
        <input type="checkbox">
        <%= f.check_box :need_contact %>
      </label>
    </div>

    <div class="ui-form-item ui-border-b">
      <%= f.label :next_contact_at, "联系日期" %>
      <%= f.text_field :next_contact_at, { placeholder: '联系日期', type: 'date' } %>
      <a href="#" class="ui-icon-close"></a>
    </div>

    <div class="ui-form-item ui-form-item-textarea ui-border-b" style="height: 160px;">
      <%= f.label :contact_log, "联系记录" %>
      <%= f.text_area :contact_log, { placeholder: '联系记录', value: @contact_log.contact_log, style: 'height: 140px;' } %>
    </div>

    <div class="ui-btn-wrap">
      <%= f.submit "保存意向", class: "ui-btn-lg ui-btn-primary" %>
    </div>
  <% end %>
  </div>
</div>
<script type="text/javascript">
  // 点击文本框关闭按钮删除内容，同时设置焦点
  $('.ui-icon-close').on('touchend', function(e) {
    var inputs = $(this.parentNode).find('input');
    inputs.val('');
    setTimeout(function(inputs) {
      inputs.focus();
    }, 100, inputs);
  });

  function refresh() {
    location.href = location.href;
  }
</script>