config/routes.rb
# encoding: UTF-8
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/20150612', as: 'rails_admin'

  devise_for :users

  root 'welcome#index'

  namespace :welcome do
    get '/' => :index
    get '/demo' => :demo
    get '/map' => :map
    get '/temp' => :temp
    get '/unsigned' => :unsigned
  end

  namespace :open do
    get '/' => :index
    get '/map' => :map
    get '/rank' => :rank
    # temp
    get '/students' => :students
    get '/coaches' => :coaches
    get '/student_sources' => :student_sources
    # for exe
    get '/lakldnfhw' => :lakldnfhw
    get '/mxl82wepoasdm' => :mxl82wepoasdm
    get '/ekz1k4xja1ve5y4r' => :ekz1k4xja1ve5y4r
  end

  namespace :contact_logs do
    get 'new_contact_log' => :new_contact_log
    post 'new_contact_log' => :new_contact_log
  end

  namespace :service do
    post 'assign_task' => :assign_task
    get 'search' => :search
    post 'daily_sign' => :daily_sign
    post 'sms_consultant' => :sms_consultant
  end

  resources :intentions do
    collection do
      post 'get_intention_list' => :get_intention_list
    end
  end

  resources :fees, only: [:index] do
    collection do
      get 'should_pay' => :should_pay
      get 'report' => :report
    end
  end

  resources :pay_units do
    get 'payments' => :payments
    member do
      get 'pay_accounts_select' => :pay_accounts_select
      get 'get_accounts_select' => :get_accounts_select
    end
  end

  resources :payments do
    get 'report_line' => :report_line
  end

  resources :students do
    resources :residence_cards
    resources :contact_logs
    resources :fees do
      resources :payments do
        post 'update_post' => :update_post
        get 'report_edit' => :report_edit
      end
      collection do
        get 'new_exams' => :new_exams
      end
    end
    member do
      post 'update_km1' => :update_km1
      post 'fee_list' => :fee_list
      post 'update_lz' => :update_lz
      post 'has_contact_task' => :has_contact_task
    end
    collection do
      post 'get_student_status' => :get_student_status
      post 'update_id_card' => :update_id_card
      get 'upload_id_card_form' => :upload_id_card_form
      post 'notify_got_number' => :notify_got_number
      post 'notify_got_card' => :notify_got_card
      get 'signed_up' => :signed_up
      get 'wait_pay' => :wait_pay
      get 'need_contact' => :need_contact
      post 'update_evaluation' => :update_evaluation
      post 'peek_before_evaluation' => :peek_before_evaluation
      get 'student_xlsx' => :student_xlsx
      get 'students_process_list' => :students_process_list
    end
  end

  resources :fees do
  end

  resources :student_sources do
    # resources :source_contracts
    resources :source_contacts
    collection do
      get 'list' => :list
      get 'new_source_contact' => :new_source_contact
      post 'new_source_contact' => :new_source_contact
    end
  end

  resources :coaches, only: [:index, :new, :show, :edit, :update, :create] do
    resources :train_services, only: [:index, :new, :show, :edit, :update, :create]
    collection do
      get 'train_services' => :train_services
      post 'train_services' => :train_services
    end
  end

  resources :work_tasks do
    collection do
      post 'process_task' => :process_task
    end
  end

  namespace :api do
    post 'notify' => :notify
  end

  namespace :m do
    root 'dashboard#index'
    namespace :dashboard do
      get '/' => :index
      post '/logout' => :logout
    end
    resources :intentions
    resources :students do
      resources :contact_logs
      member do
        get 'set_to_me' => :set_to_me
      end
      collection do
        post 'query' => :query
      end
    end
  end

end

app/models/intention.rb
# encoding: UTF-8
class Intention < ActiveRecord::Base
  enum current_status: { wait_call: 0, contacting: 1, booking: 2, wait_pay: 3, signed_up: 4, canceled: 5 }

  belongs_to :student
  belongs_to :user
  belongs_to :student_source

  validates :source, length: { maximum: 255, message: '来源名称超出长度限制' }

  def self.current_status_for_select
    current_statuses.map do |current_status, _|
      [I18n.t("current_status.#{current_status}"), current_status]
    end
  end

  def current_status_text
    I18n.t("current_status.#{current_status}")
  end

  def current_status_date
    contact_logs = student.contact_logs.where(current_status: self[:current_status])
    if contact_logs.count > 0
      contact_logs.order(created_at: :desc).first.created_at.to_date.to_s(:db)
    else
      '未知'
    end
  end

end

app/controllers/intentions_controller.rb
# encoding: UTF-8
class IntentionsController < PcApplicationController
  require 'phone_ext'
  require 'ext_calc'
  include SendSms
  include SendNotifications

  before_action :authenticate_user!
  load_and_authorize_resource
  def index
    @current_page = :intentions_path
    @intentions = Intention.all.order(updated_at: :desc, next_contact_at: :asc)
    if current_user.has_role? :jby
      @intentions = @intentions.joins(:student).where(students: { identity: 2 })
    end
    @today_intentions = @intentions.where('next_contact_at <= ? and current_status != 5', Date.today)
  end

  def new
    @student = current_user.students.build
    @student.build_intention
  end

  def create
    user_id = current_user.id
    user_id = params[:student][:contact_log][:user_id].to_i if params[:student][:contact_log][:user_id].present?
    user = User.find(user_id)
    @student = user.students.build(params_of_student)
    @student.intention.user = @student.user
    if current_user.has_role? :jby
      @student.jby!
    end
    can_update_last_contact = (params[:student][:contact_log][:has_contact_log] == '1')
    student_source_id = params[:student][:student_source][:id]
    if can_update_last_contact
      #save contact log attactched to it
      contact_log_entity = user.contact_logs.build(params_of_contact_log_in_student)
      @student.contact_logs << contact_log_entity
    else
      contact_log_entity = user.contact_logs.build(default_contact_log)
      @student.contact_logs << contact_log_entity
    end
    if @student.save
      if can_update_last_contact
        @student.intention.update(next_contact_at: contact_log_entity.next_contact_at, current_status: contact_log_entity.current_status)
        @student.update(signed_at: Date.today) if params_of_contact_log_in_student[:current_status] == 'signed_up' && @student.signed_at.nil?
        @student.update(signed_at: nil) if params_of_contact_log_in_student[:current_status] == 'canceled'
      else
        @student.intention.update(next_contact_at: Date.today, current_status: 0)
      end

      if student_source_id.is_number?
        student_source = StudentSource.find(student_source_id)
        @student.intention.student_source = student_source
      else
        @student.intention.student_source = nil
      end

      notify = {
        operator: user.name,
        message: "创建了【#{@student.name}】学员，并录入了他（她）的意向信息"
      }
      send_erp_notify(notify)

      respond_to do |format|
        format.html { redirect_to root_path }
      end
    else
      respond_to do |format|
        format.html { redirect_to :back, alert: @student.errors.messages.values.first.try(&:first) }
      end
    end
  end

  def show
    @current_page = :intention_path
    id = params[:id].to_i
    @intention = Intention.find(id)
    @student = @intention.student
    @contact_logs = @student.contact_logs.order(created_at: :desc)
  end

  def get_intention_list
    current_status = params[:current_status]
    @intentions = Intention.all
    if current_user.has_role? :jby
      @intentions = @intentions.joins(:student).where(students: { identity: 2 })
    end
    case current_status.downcase
    when 'wait_call'
      @intentions = @intentions.wait_call
    when 'contacting'
      @intentions = @intentions.contacting
    when 'booking'
      @intentions = @intentions.booking
    when 'wait_pay'
      @intentions = @intentions.wait_pay
    when 'signed_up'
      @intentions = @intentions.signed_up
    when 'should_contact'
      @intentions = @intentions.where('next_contact_at <= ? and current_status != 5', Date.today)
    end
    @intentions = @intentions.order(updated_at: :desc, next_contact_at: :asc)
    render '_index_card_intention_list', layout: false
  end

  def edit
    @current_page = :edit_intention_path
    @intention = Intention.find(params[:id])
  end

  def update
    student_source_id = params[:intention][:student_source][:id]
    @intention = Intention.find(params[:id])

    @intention.update(params_of_intention_update)
    if student_source_id.is_number?
      @intention.student_source = StudentSource.find(student_source_id)
    else
      @intention.student_source = nil
    end
    @intention.save
    notify = {
      operator: current_user.name,
      message: "更新了【#{@intention.student.name}】学员的意向信息"
    }
    send_erp_notify(notify)
    redirect_to @intention
  end

  private

  def params_of_student
    params.require(:student).permit(:name, :sex, :phone, :id_card, :address, :unit, intention_attributes: [:source])
  end

  def params_of_intention_update
    params.require(:intention).permit(:source, :current_status)
  end

  def params_of_contact_log_in_student
    params.require(:student).require(:contact_log).permit(:contact_type, :current_status, :need_contact, :next_contact_at, :contact_log, :created_at)
  end

  def default_contact_log
    {
      contact_type: 'intent',
      current_status: 'wait_call',
      need_contact: 1,
      next_contact_at: Date.today,
      contact_log: ''
    }
  end

end

app/controllers/m/intentions_controller.rb
class M::IntentionsController < MController
  before_action :authenticate_user!
  include SendNotifications

  def index
  end

  def new
    @student = current_user.students.build
    @student.build_intention
  end

  def create
    # get user
    user = current_user
    # build student of user
    @student = user.students.build(params_of_student)
    # bind intention user to student.user
    @student.intention.user = @student.user
    # pick student_source_id
    student_source_id = params[:student][:student_source][:id]
    # build default contact log
    contact_log_entity = user.contact_logs.build(default_contact_log)
    @student.contact_logs << contact_log_entity

    if @student.save
      @student.intention.update(next_contact_at: Date.today, current_status: 0)
      # bind student_source for intention
      if student_source_id.is_number?
        student_source = StudentSource.find(student_source_id)
        @student.intention.student_source = student_source
      else
        @student.intention.student_source = nil
      end

      notify = {
        operator: user.name,
        message: "通过手机创建了【#{@student.name}】学员，并录入了他（她）的意向信息"
      }
      send_erp_notify(notify)

      respond_to do |format|
        format.html { redirect_to m_student_path(@student) }
      end
    else
      respond_to do |format|
        format.html { redirect_to :back, alert: @student.errors.messages.values.first.try(&:first) }
      end
    end
  end

  def show
  end

  def edit
  end

  private

  def params_of_student
    params.require(:student).permit(:name, :sex, :phone, :id_card, :address, :unit, intention_attributes: [:source])
  end

  def default_contact_log
    {
      contact_type: 'intent',
      current_status: 'wait_call',
      need_contact: 1,
      next_contact_at: Date.today,
      contact_log: ''
    }
  end
end

app/views/intentions/_form_intention.html.erb
<div class="ui segment">
  <%= form_for(@intention, url: intention_path, method: :patch, html: { class: "ui form" }) do |f| %>
  <div class="ui error message">
    <%= render "layouts/flash" %>
  </div>

  <div class="ui one column doubling stackable grid container">
    <div class="column">
      <div class="field">
          <%= f.label :source, "意向来源" %>
          <%= f.text_field :source, { placeholder: '请输入意向来源' } %>
      </div>
      <%= f.fields_for :student_source do |ssf| %>
      <% student_source_id = (@intention.student_source.nil? ? 0 : @intention.student_source.id) %>
      <div class="field follow_create_contact_log">
        <%= ssf.label :id, "渠道来源" %>
        <%= ssf.select :id, options_for_select(StudentSource.student_source_for_select, student_source_id), {}, class: "ui dropdown student-source-name" %>
      </div>
      <% end %>
      <div class="field">
        <%= f.label :current_status, "当前状态" %>
        <%= f.select :current_status, options_for_select(Intention.current_status_for_select, @intention.current_status), {}, class: "ui dropdown current_status" %>
      </div>
    </div>
  </div>

  <div class="ui one column doubling stackable grid container">
    <div class="column">
      <%= f.submit "更新意向信息", class: "ui primary button" %>
    </div>
  </div>
  <% end %>
</div>

app/views/intentions/_form_intention_contact_log.html.erb
<div class="ui segment">
  <%= form_for(@student, url: intentions_path, method: :post, html: { class: "ui form" }) do |f| %>
  <div class="ui error message">
    <%= render "layouts/flash" %>
  </div>
  <div class="ui two column doubling stackable grid container">
    <div class="column">
      <div class="field">
        <%= f.label :name, "姓名" %>
        <%= f.text_field :name, { placeholder: '请输入姓名' } %>
      </div>
      <div class="field">
        <%= f.label :phone, "手机号" %>
        <%= f.text_field :phone, { placeholder: '请输入11位手机号码' } %>
      </div>
      <div class="grouped fields">
        <label>性别</label>
        <% [['unknown', '未知'], ['female', '女'], ['male', '男']].reverse.each do |sex_item| %>
        <div class="field">
          <div class="ui radio checkbox">
            <% if sex_item.first == @student.sex || (sex_item.first == 1 && @student.sex == 'male' )%>
            <input name="student[sex]" checked="checked" type="radio" id="student_sex_<%= sex_item.first %>" value="<%= sex_item.first %>" />
            <label for="student_sex"><%= sex_item.last %></label>
            <% else %>
            <input name="student[sex]" type="radio" id="student_sex_<%= sex_item.first %>" value="<%= sex_item.first %>" />
            <label for="student_sex"><%= sex_item.last %></label>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
      <div class="field">
        <%= f.label :id_card, "身份证号" %>
        <%= f.text_field :id_card, { placeholder: '请输入身份证号' } %>
      </div>
      <div class="field">
        <%= f.label :address, "联系地址" %>
        <%= f.text_field :address, { placeholder: '联系地址' } %>
      </div>
      <div class="field">
        <%= f.label :unit, "单位" %>
        <%= f.text_field :unit, { placeholder: '单位' } %>
      </div>
      <div class="field">
        <%= f.fields_for :intention do |pf| %>
          <%= pf.label :source, "意向来源" %>
          <%= pf.text_field :source, { placeholder: '请输入意向来源' } %>
        <% end %>
      </div>
      <%= f.fields_for :student_source do |ssf| %>
      <div class="field follow_create_contact_log">
        <%= ssf.label :id, "渠道来源" %>
        <%= ssf.select :id, options_for_select(StudentSource.student_source_for_select), {}, class: "ui dropdown student-source-name" %>
      </div>
      <% end %>
    </div>
    <div class="column">
      <%= f.fields_for :contact_log do |cf| %>
      <div class="field">
        <div class="ui toggle checkbox create_contact_log">
          <%= cf.check_box :has_contact_log, checked: true %>
          <%= cf.label :has_contact_log, "创建联系记录" %>
        </div>
      </div>
      <% if current_user.has_role? :can_choose_user %>
      <div class="field follow_create_contact_log">
        <%= cf.label :user_id, "创建人" %>
        <%= cf.select :user_id, options_for_select(User.user_for_select, current_user.id), {}, class: "ui dropdown user-id" %>
      </div>
      <% end %>
      <div class="field follow_create_contact_log">
        <%= cf.label :contact_type, "联系类型" %>
        <%= cf.select :contact_type, options_for_select(ContactLog.contact_types_for_select), {}, class: "ui dropdown contact_type" %>
      </div>

      <div class="field follow_create_contact_log">
        <%= cf.label :current_status, "当前状态" %>
        <%= cf.select :current_status, options_for_select(ContactLog.current_status_for_select), {}, class: "ui dropdown current_status" %>
      </div>

      <div class="field follow_create_contact_log">
        <%= cf.label :created_at, "创建日期" %>
        <%= cf.text_field :created_at, value: Date.today.to_s(:db), class: 'datepicker' %>
      </div>

      <div class="field follow_create_contact_log">
        <div class="ui toggle checkbox need_contact">
          <%= cf.check_box :need_contact %>
          <%= cf.label :need_contact, "需要联系" %>
        </div>
      </div>

      <div class="field follow_create_contact_log">
        <%= cf.label :next_contact_at, "联系日期" %>
        <%= cf.text_field :next_contact_at, class: 'datepicker' %>
      </div>

      <div class="field follow_create_contact_log">
        <%= cf.label :contact_log, "联系记录" %>
        <%= cf.text_area :contact_log, rows: 10 %>
      </div>
      <% end %>
    </div>
  </div>
  <div class="ui one column doubling stackable grid container">
    <div class="column">
      <%= f.submit "保存意向", class: "ui primary button" %>
    </div>
  </div>
  <% end %>
</div>

app/views/intentions/_index_assign_task.html.erb
<div class="ui modal assign-task">
  <i class="close icon"></i>
  <div class="header">
    指定处理人
  </div>
  <div class="content">
    <div class="ui form">
      <div class="field">
        <label for="processor">处理人</label>
        <select class="ui search selection dropdown" name="processor" id="processor">
          <option></option>
          <% User.all.each do |user| %>
          <option value="<%= user.id %>"><%= user.name %></option>
          <% end %>
        </select>
      </div>
      <div class="field">
        <label for="task_date">日期</label>
        <input type="text" name="task_date" id="task_date" class="datepicker" />
      </div>
      <div class="field">
        <label for="task_type">备注说明</label>
        <input type="text" name="task_type" id="task_type" />
      </div>
      <div class="field">
        <label for="preview">预览消息</label>
        <div name="preview" style="border: solid 1px #ccc;border-radius: 5px;padding: 5px;">
          发布人：<%= current_user.name %>（手机：<%= current_user.phone %>）<br>
          发布时间：<span class="t red">[由实际发布时间决定]</span><br>
          消息：<br><span class="t red">[处理人]</span>你好，请于<span class="t red">[日期]</span>处理<span class="t red">[当前学员]</span>学员（手机：<span class="t red">[学员号码]</span>）的业务<br><span class="t red">[备注说明]</span>
        </div>
      </div>
    </div>
  </div>
  <div class="actions">
    <div class="ui black deny button">
      不用了
    </div>
    <div class="ui positive right labeled icon button">
      好的就这样
      <i class="checkmark icon"></i>
    </div>
  </div>
</div>

app/views/intentions/_index_card_intention_list.html.erb
<ul class="intention-cards">
  <% @intentions.each do |intention| %>
  <%
    student = intention.student
    last_contact = student.contact_logs.last
  %>
  <li class="intention-card" data-user-name="<%= student.name %>">
    <div class="ui card">
      <div class="ui slide masked reveal image">
        <% if intention.next_contact_at %>
        <div class="img-comment">下次联系: <%= intention.next_contact_at.to_s(:db) %>
        </div>
        <% end %>
        <%= image_tag student.id_card_pic.url, class: 'visible content' %>
        <%= image_tag student.id_card_back_pic.url, class: 'hidden content' %>
      </div>
      <div class="content">
        <div class="header">
          <%= link_to "#{student.name}", student_path(intention.student), { class: 'header', target: '_blank' } %>
          (<%= link_to "意向信息", intention_path(intention), { class: 'meta', target: '_blank'} %>)
        </div>
        <div class="meta">
          <span class="date">当前状态：<%= intention.current_status_text %>[<%= intention.current_status_date %>]</span>
          <% unless student.coach.nil? %>
          <br>
          <span class="date">教练：<%= student.coach.name %>[ <%= PhoneExt.format_phone(student.coach.phone) %> ]</span>
          <% end %>
        </div>
        <div class="description box">
          <div style="border-bottom: solid 1px #ccc;padding: 5px;background-color: #eee;">备注</div>
          <div style="border-bottom: solid 1px #ccc;padding: 5px;">
            <% if student.remarks.nil? %>
            <span style="color: #ccc;">【暂无备注】</span>
            <% else %>
            <%= student.remarks.gsub(/\n/, '<br>').html_safe %>
            <% end %>
          </div>
          <%
          contact_logs = student.contact_logs.order(updated_at: :desc)
          contact_log = contact_logs.first if contact_logs.count > 0
          %>
          <% if contact_logs.count > 0 %>
          <div style="border-bottom: solid 1px #ccc;padding: 5px;background-color: #eee;">上次联系</div>
          <div style="padding: 5px;max-height: 150px;overflow-y: auto;">
            <% if contact_log.present? %>
            <%= contact_log.contact_log.gsub(/\n/, '<br>').html_safe %>
            <% end %>
          </div>
          <% end %>
        </div>
      </div>
      <div class="extra content">
        <a>
          <i class="user icon"></i>
          <% if last_contact.present? && last_contact.user.present? %>
          上次联系人：<%= last_contact.user.name %>
          <% else %>
          上次联系人：未知
          <% end %>
        </a>
      </div>
      <div class="extra content user-action" data-student-id="<%= student.id %>">
        <a class="ui button padded">指派任务</a>
      </div>
    </div>
  </li>
  <% end %>
</ul>

<% if @intentions.count <= 0 then %>
<div class="ui very raised text container segment">
  <div class="ui container">
    未找到数据
  </div>
</div>
<% end %>

app/views/intentions/_show_next_contact_date.html.erb
<% next_contact_date = @intention.next_contact_at %>
<% if next_contact_date.nil? %>
<span class="padded-tag">请尽快联系</span>
<% else %>
  <% if next_contact_date < Time.now.to_date then %>
  <span style="color: red;"><%= next_contact_date.to_s(:db) %></span>
  <span class="padded-tag red">快联系啊</span>
  <% elsif next_contact_date == Time.now.to_date then %>
  <span style="color: green;"><%= next_contact_date.to_s(:db) %></span>
  <% else %>
  <%= next_contact_date.to_s(:db) %>
  <% end %>
<% end %>

app/views/intentions/edit.html.erb
<link rel="stylesheet" href="/datetimepicker/themes/classic.css" id="theme_base">
<link rel="stylesheet" href="/datetimepicker/themes/classic.date.css" id="theme_date">
<% content_for :title, "#{@intention.student.name} - 编辑意向信息" %>
<div class="intention">
  <%= render 'form_intention' %>
</div>
<script type="text/javascript">
  (function() {
    $('.ui.dropdown.current_status').dropdown();
    $('.ui.dropdown.student-source-name').dropdown();
  })();
</script>

app/views/intentions/show.html.erb
<% content_for :title, "[#{@intention.student.name}]的学车意向 - 极速学车ERP系统" %>
<div class="intention intention-detail">
  <div class="padding-container">
    <div class="ui raised text segment">
      <div class="ui three column middle aligned very relaxed stackable grid">
        <div class="column">
          姓名：<%= @student.name %>
        </div>
        <div class="column">
          性别：<%= t("sexs.#{@student.sex}") %>
        </div>
        <div class="column">
          年龄：<%= ExtCalc.age_from_idcard(@student.id_card) %>
        </div>
      </div>
      <div class="ui three column middle aligned very relaxed stackable grid">
        <div class="column">
          手机：<%= @student.phone_divided.html_safe %>
        </div>
        <div class="column">
          身份证：<%= @student.id_card %>
        </div>
        <div class="column">
          联系地址：<%= @student.address %>
        </div>
      </div>
      <div class="ui three column middle aligned very relaxed stackable grid">
        <div class="column">
          单位：<%= @student.unit %>
        </div>
        <div class="column">
          对接人：<%= @intention.user.present? ? @intention.user.name : '-' %>
        </div>
        <div class="column">
          下次联系：<%= render partial: 'show_next_contact_date' %>
        </div>
      </div>
      <div class="ui three column middle aligned very relaxed stackable grid">
        <div class="column">
          当前状态：<%= t("current_status.#{@intention.current_status}") %>
        </div>
        <div class="column">
          <% if @student.coach.present? %>
          教练：<%= "#{@student.coach.name} [ #{PhoneExt.format_phone(@student.coach.phone)} ]" %>
          <% else %>
          教练：<span class="t red">尚未指定教练</span>
          <% end %>
        </div>
        <div class="column">
        </div>
      </div>
    </div>
    <div class="ui raised text segment">
      <%= link_to new_student_contact_log_path(@student.id) do %>
        <div class="ui primary labeled icon button">
          新的跟踪
          <i class="add icon"></i>
        </div>
      <% end %>
      <%= link_to edit_intention_path(@intention) do %>
        <div class="ui teal labeled icon button">
          编辑意向信息
          <i class="edit icon"></i>
        </div>
      <% end %>
      <div class="ui teal labeled icon button sms-consultant">
        发送学车顾问信息
        <i class="mail icon"></i>
      </div>
    </div>
    <div>
      <table class="ui celled table" style="table-layout: fixed;">
        <colgroup>
          <col style="width: 100px;" />
          <col style="width: 100px;" />
          <col style="width: 100px;" />
          <col style="width: 100px;" />
          <col />
        </colgroup>
        <thead>
          <tr>
            <th>日期</th>
            <th>处理人</th>
            <th>类型</th>
            <th>下次联系</th>
            <th>详情</th>
          </tr>
        </thead>
        <tbody>
          <% @contact_logs.order(updated_at: :desc).each do |contact_log| %>
          <%
            updated_at_date = contact_log.updated_at.localtime
            next_contact_at = contact_log.next_contact_at
          %>
          <tr>
            <td style="text-align: center;">
              <%= updated_at_date.to_s(:db) %>
            </td>
            <td>
              <%= contact_log.user.name %>
            </td>
            <td>
              <%= I18n.t("contact_types.#{contact_log.contact_type}") %>
            </td>
            <% if next_contact_at == 0 then %>
              <td>不需要</td>
            <% else %>
              <% if next_contact_at.nil? %>
              <td>-</td>
              <% else %>
              <td><%= next_contact_at.to_date.to_s(:db) %></td>
              <% end %>
            <% end %>
            <td>
              <i class="chevron down icon" style="border: solid 1px #ccc;width: 30px;height: 20px;cursor: pointer;float: right;"></i>
              <p class="one-line" title="<%= contact_log.contact_log %>"><%= contact_log.contact_log %></p>
            </td>
          </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <th colspan="5">
              <div class="ui right floated pagination menu">
                <a class="icon item">
                  <i class="left chevron icon"></i>
                </a>
                <a class="item">1</a>
                <a class="item">2</a>
                <a class="item">3</a>
                <a class="item">4</a>
                <a class="icon item">
                  <i class="right chevron icon"></i>
                </a>
              </div>
            </th>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>
<script type="text/javascript">
  $('.chevron.icon').on('click', function () {
    var contentJq = $(this).parent().find('p');
    var iconJq = $(this);
    if (iconJq.hasClass('down')) {
      //释放内容
      contentJq.removeClass('one-line');
      //改箭头方向
      iconJq.removeClass('down');
      iconJq.addClass('up');
      //内容替换
      contentJq.html(contentJq.html().replace(/\n/g, '<br>'));
    } else {
      //回收内容
      contentJq.addClass('one-line');
      //改箭头方向
      iconJq.removeClass('up');
      iconJq.addClass('down');
      //恢复内容
      contentJq.html(contentJq.attr('title'));
    }
  });
  $('.sms-consultant').on('click', function() {
    $.post('/service/sms_consultant', {
      'student_id': <%= @student.id %>
    }).success(function(data) {
      if (data && data.msg_code == 'success') {
        alert('发送消息成功！');
      } else {
        alert('发送消息错误，请联系管理员！');
      }
    }).error(function(data) {
      alert('发送消息错误，请联系管理员！');
    });
  });
</script>