config/routes.rb
# encoding: UTF-8
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/20150612', as: 'rails_admin'

  devise_for :users

  root 'welcome#index'

  namespace :welcome do
    get '/' => :index
    get '/demo' => :demo
    get '/map' => :map
    get '/temp' => :temp
    get '/unsigned' => :unsigned
  end

  namespace :open do
    get '/' => :index
    get '/map' => :map
    get '/rank' => :rank
    # temp
    get '/students' => :students
    get '/coaches' => :coaches
    get '/student_sources' => :student_sources
    # for exe
    get '/lakldnfhw' => :lakldnfhw
    get '/mxl82wepoasdm' => :mxl82wepoasdm
    get '/ekz1k4xja1ve5y4r' => :ekz1k4xja1ve5y4r
  end

  namespace :contact_logs do
    get 'new_contact_log' => :new_contact_log
    post 'new_contact_log' => :new_contact_log
  end

  namespace :service do
    post 'assign_task' => :assign_task
    get 'search' => :search
    post 'daily_sign' => :daily_sign
    post 'sms_consultant' => :sms_consultant
  end

  resources :intentions do
    collection do
      post 'get_intention_list' => :get_intention_list
    end
  end

  resources :fees, only: [:index] do
    collection do
      get 'should_pay' => :should_pay
      get 'report' => :report
    end
  end

  resources :pay_units do
    get 'payments' => :payments
    member do
      get 'pay_accounts_select' => :pay_accounts_select
      get 'get_accounts_select' => :get_accounts_select
    end
  end

  resources :payments do
    get 'report_line' => :report_line
  end

  resources :students do
    resources :residence_cards
    resources :contact_logs
    resources :fees do
      resources :payments do
        post 'update_post' => :update_post
        get 'report_edit' => :report_edit
      end
      collection do
        get 'new_exams' => :new_exams
      end
    end
    member do
      post 'update_km1' => :update_km1
      post 'fee_list' => :fee_list
      post 'update_lz' => :update_lz
      post 'has_contact_task' => :has_contact_task
    end
    collection do
      post 'get_student_status' => :get_student_status
      post 'update_id_card' => :update_id_card
      get 'upload_id_card_form' => :upload_id_card_form
      post 'notify_got_number' => :notify_got_number
      post 'notify_got_card' => :notify_got_card
      get 'signed_up' => :signed_up
      get 'wait_pay' => :wait_pay
      get 'need_contact' => :need_contact
      post 'update_evaluation' => :update_evaluation
      post 'peek_before_evaluation' => :peek_before_evaluation
      get 'student_xlsx' => :student_xlsx
      get 'students_process_list' => :students_process_list
    end
  end

  resources :fees do
  end

  resources :student_sources do
    # resources :source_contracts
    resources :source_contacts
    collection do
      get 'list' => :list
      get 'new_source_contact' => :new_source_contact
      post 'new_source_contact' => :new_source_contact
    end
  end

  resources :coaches, only: [:index, :new, :show, :edit, :update, :create] do
    resources :train_services, only: [:index, :new, :show, :edit, :update, :create]
    collection do
      get 'train_services' => :train_services
      post 'train_services' => :train_services
    end
  end

  resources :work_tasks do
    collection do
      post 'process_task' => :process_task
    end
  end

  namespace :api do
    post 'notify' => :notify
  end

  namespace :m do
    root 'dashboard#index'
    namespace :dashboard do
      get '/' => :index
      post '/logout' => :logout
    end
    resources :intentions
    resources :students do
      resources :contact_logs
      member do
        get 'set_to_me' => :set_to_me
      end
      collection do
        post 'query' => :query
      end
    end
  end

end

app/models/student_source.rb
class StudentSource < ActiveRecord::Base
  enum gender: { unknown: 2, male: 1, female: 0 }
  enum source_type: { student: 0, employee: 1, shareholder: 2 }

  belongs_to :school
  belongs_to :user

  has_many :source_contacts
  has_many :intentions
  has_many :source_contracts

  def self.student_source_for_select
    student_source_collection = [['[空]', '']]
    StudentSource.all.each do |student_source|
      student_source_collection << [student_source.name, student_source.id]
    end
    student_source_collection
  end

  def gender_text
    I18n.t("student_source.gender.#{gender}", gender)
  end

  def self.gender_for_select
    genders.map do |gender, _|
      [I18n.t("student_source.gender.#{gender}"), gender]
    end
  end

  def self.source_type_for_select
    source_types.map do |source_type, _|
      [I18n.t("student_source.source_type.#{source_type}"), source_type]
    end
  end
end

app/controllers/student_sources_controller.rb
class StudentSourcesController < PcApplicationController
  require 'phone_ext'
  before_action :set_student_source, only: [:show, :edit, :update]
  load_and_authorize_resource
  def list
    @current_page = :list_student_sources_path
    @student_sources = StudentSource.all.order(signed_at: :desc)
  end

  def new_source_contact
    if request.method.downcase == 'post'
      redirect_to new_student_source_source_contact_path(params[:student_source_id])
    end
  end

  def index
    @current_page = :student_sources_path
  end

  def new
    @current_page = :student_sources_path_new
    @student_source = @student_source || current_user.student_sources.new
  end

  def show
    @current_page = :student_source_path
  end

  def edit
    @current_page = :edit_student_source_path
  end

  def create
    @student_source = current_user.student_sources.build(student_source_params)
    if @student_source.save
      respond_to do |format|
        format.html { redirect_to student_sources_path }
      end
    else
      respond_to do |format|
        format.html { redirect_to :back, alert: @student.errors.messages.values.first.try(&:first) }
      end
    end
  end

  def update
    if @student_source.update(student_source_params)
      respond_to do |format|
        format.html { redirect_to student_source_path }
      end
    else
      respond_to do |format|
        format.html { redirect_to :back, alert: @student.errors.messages.values.first.try(&:first) }
      end
    end
  end

  private

  def set_student_source
    @student_source = StudentSource.find(params[:id])
  end

  def student_source_params
    params.require(:student_source).permit(:name, :phone, :gender, :id_card, :school_id, :qq, :email, :alipay, :qr_code, :remarks, :signed_at, :deposit, :deposit_paid, :source_type)
  end
end

app/views/student_sources/_form_edit.html.erb
<div class="ui segment">
  <%= form_for(@student_source, url: student_source_path, method: :patch, html: { class: "ui form" }) do |f| %>
  <div class="ui error message">
    <%= render "layouts/flash" %>
  </div>
  <div class="ui one column doubling stackable grid container">
    <div class="column">
      <div class="field">
        <%= f.label :name, "姓名" %>
        <%= f.text_field :name, { placeholder: '请输入姓名' } %>
      </div>
      <div class="field">
        <%= f.label :gender, "性别" %>
        <%= f.select :gender, options_for_select(StudentSource.gender_for_select, @student_source.gender), {}, class: "ui dropdown gender" %>
      </div>
      <div class="field">
        <%= f.label :phone, "手机号" %>
        <%= f.text_field :phone, { placeholder: '请输入11位手机号码' } %>
      </div>
      <div class="field">
        <%= f.label :id_card, "身份证号" %>
        <%= f.text_field :id_card, { placeholder: '请输入身份证号' } %>
      </div>
      <div class="field">
        <%= f.label :signed_at, "签约日期" %>
        <%= f.text_field :signed_at, class: 'datepicker' %>
      </div>
      <div class="field">
        <%= f.label :deposit, "应缴押金" %>
        <%= f.text_field :deposit %>
      </div>
      <div class="field">
        <%= f.label :deposit_paid, "实缴押金" %>
        <%= f.text_field :deposit_paid %>
      </div>
      <div class="field">
        <%= f.label :qr_code, "推广二维码" %>
        <%= f.text_field :qr_code, { placeholder: '请输入推广二维码的代码' } %>
      </div>
      <div class="field">
        <%= f.label :qq, "QQ" %>
        <%= f.text_field :qq, { placeholder: '请输入QQ号码' } %>
      </div>
      <div class="field">
        <%= f.label :email, "Email" %>
        <%= f.text_field :email, { placeholder: '请输入邮箱地址' } %>
      </div>
      <div class="field">
        <%= f.label :alipay, "支付宝" %>
        <%= f.text_field :alipay, { placeholder: '请输入支付宝账号' } %>
      </div>
      <div class="field">
        <%= f.label :source_type, "身份" %>
        <%= f.select :source_type, options_for_select(StudentSource.source_type_for_select, @student_source.source_type), {}, class: "ui fluid search dropdown source-type" %>
      </div>
      <div class="field">
        <%= f.label :school_id, "学校" %>
        <%= f.select :school_id, options_for_select(School.school_for_select, @student_source.school_id), {}, class: "ui fluid search dropdown school" %>
      </div>
      <div class="field">
        <%= f.label :remarks, "备注" %>
        <%= f.text_area :remarks, rows: 10, value: @student_source.remarks %>
      </div>
    </div>
  </div>
  <div class="ui one column doubling stackable grid container">
    <div class="column">
      <%= f.submit "保存渠道", class: "ui primary button" %>
    </div>
  </div>
  <% end %>
</div>

app/views/student_sources/_form_new.html.erb
<div class="ui segment">
  <%= form_for(@student_source, url: student_sources_path, method: :post, html: { class: "ui form" }) do |f| %>
  <div class="ui error message">
    <%= render "layouts/flash" %>
  </div>
  <div class="ui one column doubling stackable grid container">
    <div class="column">
      <div class="field">
        <%= f.label :name, "姓名" %>
        <%= f.text_field :name, { placeholder: '请输入姓名' } %>
      </div>
      <div class="field">
        <%= f.label :gender, "性别" %>
        <%= f.select :gender, options_for_select(StudentSource.gender_for_select), {}, class: "ui dropdown gender" %>
      </div>
      <div class="field">
        <%= f.label :phone, "手机号" %>
        <%= f.text_field :phone, { placeholder: '请输入11位手机号码' } %>
      </div>
      <div class="field">
        <%= f.label :id_card, "身份证号" %>
        <%= f.text_field :id_card, { placeholder: '请输入身份证号' } %>
      </div>
      <div class="field">
        <%= f.label :signed_at, "签约日期" %>
        <%= f.text_field :signed_at, class: 'datepicker' %>
      </div>
      <div class="field">
        <%= f.label :deposit, "应缴押金" %>
        <%= f.text_field :deposit %>
      </div>
      <div class="field">
        <%= f.label :deposit_paid, "实缴押金" %>
        <%= f.text_field :deposit_paid %>
      </div>
      <div class="field">
        <%= f.label :qr_code, "推广二维码" %>
        <%= f.text_field :qr_code, { placeholder: '请输入推广二维码的代码' } %>
      </div>
      <div class="field">
        <%= f.label :qq, "QQ" %>
        <%= f.text_field :qq, { placeholder: '请输入QQ号码' } %>
      </div>
      <div class="field">
        <%= f.label :email, "Email" %>
        <%= f.text_field :email, { placeholder: '请输入邮箱地址' } %>
      </div>
      <div class="field">
        <%= f.label :alipay, "支付宝" %>
        <%= f.text_field :alipay, { placeholder: '请输入支付宝账号' } %>
      </div>
      <div class="field">
        <%= f.label :school_id, "学校" %>
        <%= f.select :school_id, options_for_select(School.school_for_select), {}, class: "ui fluid search dropdown school" %>
      </div>
      <div class="field">
        <%= f.label :remarks, "备注" %>
        <%= f.text_area :remarks, rows: 10, value: @student_source.remarks %>
      </div>
    </div>
  </div>
  <div class="ui one column doubling stackable grid container">
    <div class="column">
      <%= f.submit "保存渠道", class: "ui primary button" %>
    </div>
  </div>
  <% end %>
</div>

app/views/student_sources/edit.html.erb
<link rel="stylesheet" href="/datetimepicker/themes/classic.css" id="theme_base">
<link rel="stylesheet" href="/datetimepicker/themes/classic.date.css" id="theme_date">
<% content_for :title, "编辑 #{@student_source.name} - 极速学车ERP系统" %>
<div class="student">
  <%= render 'form_edit' %>
</div>
<script type="text/javascript">
  (function() {
    $('.ui.dropdown.gender').dropdown();
    $('.ui.dropdown.school').dropdown();
    $('.ui.dropdown.source-type').dropdown();
    $('.datepicker').pickadate();
    <% if flash[:alert] %>
    $('.form').addClass('error');
    <% end %>
  })();
</script>

app/views/student_sources/index.html.erb
<% content_for :title, "渠道管理 - 极速学车ERP系统" %>
<div class="student-source">
  <div class="ui grid">
    <div class="eight wide column">
      <div class="ui raised text segment" style="margin-top: 10px;">
        <h2 class="ui header">渠道录入</h2>
        <p>和渠道签约后，需要立即录入</p>
        <%= link_to new_student_source_path do %>
          <div class="ui primary labeled icon button">
            添加渠道
            <i class="add icon"></i>
          </div>
        <% end %>
        <%= link_to '渠道详表', list_student_sources_path, class: 'ui primary button' %>
      </div>
    </div>
    <div class="eight wide column">
      <div class="ui raised text segment" style="margin-top: 10px;">
        <h2 class="ui header">渠道维护</h2>
        <p>渠道的建立是艰辛的，所以维护很重要，很重要，很重要</p>
        <%= link_to new_source_contact_student_sources_path do %>
          <div class="ui primary labeled icon button">
            渠道跟踪
            <i class="add icon"></i>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/student_sources/list.html.erb
<% content_for :title, "渠道详表 - 渠道管理 - 极速学车ERP系统" %>
<div class="ui segment student-source">
  <table class="ui teal striped sortable celled table">
    <thead>
      <tr>
        <th class="one wide">序号</th>
        <th class="one wide">姓名</th>
        <th class="two wide">学校</th>
        <th class="one wide">区</th>
        <th class="one wide center aligned">性别</th>
        <th class="two wide center aligned">手机</th>
        <th class="two wide center aligned">QQ</th>
        <th class="one wide center aligned sorted descending">签约日期</th>
        <th class="one wide center aligned">实缴/应缴</th>
        <th class="one wide center aligned">意向</th>
        <th class="one wide center aligned">已报名</th>
        <th class="two wide">操作</th>
      </tr>
    </thead>
    <tbody>
      <% @student_sources.each_with_index do |ss, index| %>
      <tr>
        <td class="middle center aligned"><%= (index + 1).to_s.rjust(3, '0') %></td>
        <td class="middle aligned"><%= ss.name %></td>
        <td class="middle aligned"><%= ss.school.name if ss.school.present? %></td>
        <td class="middle aligned"><%= ss.school.district if ss.school.present? %></td>
        <td class="middle center aligned"><%= ss.gender_text %></td>
        <td class="middle aligned phone"><%= PhoneExt.format_phone(ss.phone) if ss.phone.present? %></td>
        <td class="middle"><%= ss.qq if ss.qq.present? %></td>
        <td class="middle aligned date-time"><%= ss.signed_at.nil? ? '-' : ss.signed_at.to_date.to_s(:db) %></td>
        <td class="middle center aligned"><%= number_with_precision(ss.deposit_paid.to_f, precision: 0) %> / <%= number_with_precision(ss.deposit.to_f, precision: 0) %></td>
        <td class="middle aligned number"><%= ss.intentions.count %></td>
        <td class="middle aligned number"><%= ss.intentions.signed_up.count %></td>
        <td class="middle aligned">
          <%= link_to '详情', student_source_path(ss), { class: 'small-button' } %>
          <%= link_to '编辑', edit_student_source_path(ss), { class: 'small-button' } %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script type="text/javascript">
  $('table').tablesort();
</script>

app/views/student_sources/new.html.erb
<link rel="stylesheet" href="/datetimepicker/themes/classic.css" id="theme_base">
<link rel="stylesheet" href="/datetimepicker/themes/classic.date.css" id="theme_date">
<% content_for :title, "登记渠道 - 极速学车ERP系统" %>
<div class="student">
  <%= render 'form_new' %>
</div>
<script type="text/javascript">
  (function() {
    $('.ui.dropdown.gender').dropdown();
    $('.ui.dropdown.school').dropdown();
    <% if flash[:alert] %>
    $('.form').addClass('error');
    <% end %>
  })();
</script>

app/views/student_sources/new_source_contact.html.erb
<% content_for :title, "选择渠道 - 创建联系记录 - 极速学车ERP系统" %>
<div class="source-contact">
<%= form_tag('/student_sources/new_source_contact', method: "post", class: 'ui form', id: 'choose_student_source') do |f| %>
  <div class="field">
    <%= label_tag :student_source_id, "渠道" %>
    <%= select_tag :student_source_id, options_for_select(StudentSource.student_source_for_select), { class: 'ui search selection dropdown' } %>
  </div>
  <div class="div-btn">
    <%= submit_tag "下一步", class: "ui primary button" %>
  </div>
<% end %>
</div>
<script type="text/javascript">
  $('.ui.search.selection.dropdown').dropdown();
  $('#choose_student_source').submit(function() {
    if (!$("select[name='student_source_id']").val()) return false;
  });
</script>

app/views/student_sources/show.html.erb
<% content_for :title, "#{@student_source.name} - 渠道管理 - 极速学车ERP系统" %>
<div class="student-source">
  <div class="padding-container">
    <div class="ui raised text segment">
      <div class="ui three column middle aligned very relaxed stackable grid">
        <div class="column">
          姓名：<%= @student_source.name %>
        </div>
        <div class="column">
          性别：<%= @student_source.gender_text %>
        </div>
        <div class="column">
          年龄：未实现功能
        </div>
      </div>
      <div class="ui three column middle aligned very relaxed stackable grid">
        <div class="column">
          手机：<%= PhoneExt.format_phone(@student_source.phone) %>
        </div>
        <div class="column">
          身份证：<%= @student_source.id_card %>
        </div>
        <div class="column">
          学校: <%= @student_source.school.name if @student_source.school.present? %>
        </div>
      </div>
      <div class="ui three column middle aligned very relaxed stackable grid">
        <div class="column">
          QQ：<%= @student_source.qq %>
        </div>
        <div class="column">
          支付宝：<%= @student_source.alipay %>
        </div>
        <div class="column">
          二维码: <%= @student_source.qr_code %>
        </div>
      </div>
      <div class="ui three column middle aligned very relaxed stackable grid">
        <div class="column">
          签约日期：<%= @student_source.signed_at.to_date.to_s(:db) if @student_source.signed_at.present? %>
        </div>
        <div class="column">
        </div>
        <div class="column">
        </div>
      </div>
    </div>
    <div class="ui top attached tabular menu">
      <a class="item active" data-tab="contacts">联系记录</a>
      <a class="item" data-tab="achievement">报名成功</a>
      <a class="item" data-tab="intentions">所有意向</a>
    </div>
    <div class="ui bottom attached tab segment active" data-tab="contacts">
      <div>
        <%= link_to new_student_source_source_contact_path(@student_source) do %>
          <div class="ui primary labeled icon button">
            联系渠道
            <i class="add icon"></i>
          </div>
        <% end %>
      </div>
      <div>
        <table class="ui teal striped sortable celled table">
          <thead>
            <tr>
              <th class="two wide center aligned sorted descending">日期</th>
              <th class="four wide">标题</th>
              <th class="two wide center aligned">业务类型</th>
              <th class="eight wide">概要</th>
            </tr>
          </thead>
          <tbody>
            <% @student_source.source_contacts.each do |sc| %>
            <tr>
              <td class="middle aligned center aligned"><%= sc.created_at.to_date.to_s(:db) %></td>
              <td class="middle aligned"><%= sc.title %></td>
              <td class="middle aligned center aligned"><%= sc.business %></td>
              <td class="top aligned text-ellipsis long content" data-text="<%= sc.content %>"><%= sc.content %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="ui bottom attached tab segment" data-tab="achievement">
      <table class="ui teal striped sortable celled table">
        <thead>
          <tr>
            <th class="two wide center aligned sorted descending">创建日期</th>
            <th class="four wide">学员</th>
            <th class="ten wide center aligned">报名日期</th>
          </tr>
        </thead>
        <tbody>
          <% @student_source.intentions.where(current_status: 4).order(created_at: :desc).each do |intention| %>
          <tr>
            <td class="middle aligned center aligned"><%= intention.created_at.to_date.to_s(:db) %></td>
            <td class="middle aligned"><%= link_to "#{intention.student.name}", intention_path(intention), { target: '_blank' } %></td>
            <td class="middle aligned center aligned"><%= intention.student.signed_at.to_date.to_s(:db) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="ui bottom attached tab segment" data-tab="intentions">
      <table class="ui teal striped sortable celled table">
        <thead>
          <tr>
            <th class="two wide center aligned sorted descending">创建日期</th>
            <th class="four wide">学员</th>
            <th class="six wide center aligned">最新状态</th>
            <th class="four wide center aligned">最新联系</th>
          </tr>
        </thead>
        <tbody>
          <% @student_source.intentions.order(created_at: :desc).each do |intention| %>
          <tr>
            <td class="middle aligned center aligned"><%= intention.created_at.to_date.to_s(:db) %></td>
            <td class="middle aligned"><%= link_to "#{intention.student.name}", intention_path(intention), { target: '_blank' } %></td>
            <td class="middle aligned center aligned"><%= intention.current_status_text %></td>
            <% contact_logs_desc = intention.student.contact_logs.order(created_at: :desc) %>
            <% if contact_logs_desc.count > 0 %>
            <td class="middle aligned center aligned"><%= contact_logs_desc.first.created_at.to_date.to_s(:db) %></td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<script type="text/javascript">
  $('table').tablesort();
  $(".table > tbody > tr > td.content").mouseenter(function() {
    $(this).css('white-space', 'initial');
    $(this).html($(this).html().replace(/\n/g, '<br>'));
    $(this).hide();
    $(this).fadeIn();
  });
  $(".table > tbody > tr > td.content").mouseleave(function() {
    $(this).css('white-space', 'nowrap');
    $(this).html($(this).attr('data-text'));
    $(this).fadeIn();
  });
  $('.menu .item').tab();
</script>