config/routes.rb
# encoding: UTF-8
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/20150612', as: 'rails_admin'

  devise_for :users

  root 'welcome#index'

  namespace :welcome do
    get '/' => :index
    get '/demo' => :demo
    get '/map' => :map
    get '/temp' => :temp
    get '/unsigned' => :unsigned
  end

  namespace :open do
    get '/' => :index
    get '/map' => :map
    get '/rank' => :rank
    # temp
    get '/students' => :students
    get '/coaches' => :coaches
    get '/student_sources' => :student_sources
    # for exe
    get '/lakldnfhw' => :lakldnfhw
    get '/mxl82wepoasdm' => :mxl82wepoasdm
    get '/ekz1k4xja1ve5y4r' => :ekz1k4xja1ve5y4r
  end

  namespace :contact_logs do
    get 'new_contact_log' => :new_contact_log
    post 'new_contact_log' => :new_contact_log
  end

  namespace :service do
    post 'assign_task' => :assign_task
    get 'search' => :search
    post 'daily_sign' => :daily_sign
    post 'sms_consultant' => :sms_consultant
  end

  resources :intentions do
    collection do
      post 'get_intention_list' => :get_intention_list
    end
  end

  resources :fees, only: [:index] do
    collection do
      get 'should_pay' => :should_pay
      get 'report' => :report
    end
  end

  resources :pay_units do
    get 'payments' => :payments
    member do
      get 'pay_accounts_select' => :pay_accounts_select
      get 'get_accounts_select' => :get_accounts_select
    end
  end

  resources :payments do
    get 'report_line' => :report_line
  end

  resources :students do
    resources :residence_cards
    resources :contact_logs
    resources :fees do
      resources :payments do
        post 'update_post' => :update_post
        get 'report_edit' => :report_edit
      end
      collection do
        get 'new_exams' => :new_exams
      end
    end
    member do
      post 'update_km1' => :update_km1
      post 'fee_list' => :fee_list
      post 'update_lz' => :update_lz
      post 'has_contact_task' => :has_contact_task
    end
    collection do
      post 'get_student_status' => :get_student_status
      post 'update_id_card' => :update_id_card
      get 'upload_id_card_form' => :upload_id_card_form
      post 'notify_got_number' => :notify_got_number
      post 'notify_got_card' => :notify_got_card
      get 'signed_up' => :signed_up
      get 'wait_pay' => :wait_pay
      get 'need_contact' => :need_contact
      post 'update_evaluation' => :update_evaluation
      post 'peek_before_evaluation' => :peek_before_evaluation
      get 'student_xlsx' => :student_xlsx
      get 'students_process_list' => :students_process_list
    end
  end

  resources :fees do
  end

  resources :student_sources do
    # resources :source_contracts
    resources :source_contacts
    collection do
      get 'list' => :list
      get 'new_source_contact' => :new_source_contact
      post 'new_source_contact' => :new_source_contact
    end
  end

  resources :coaches, only: [:index, :new, :show, :edit, :update, :create] do
    resources :train_services, only: [:index, :new, :show, :edit, :update, :create]
    collection do
      get 'train_services' => :train_services
      post 'train_services' => :train_services
    end
  end

  resources :work_tasks do
    collection do
      post 'process_task' => :process_task
    end
  end

  namespace :api do
    post 'notify' => :notify
  end

  namespace :m do
    root 'dashboard#index'
    namespace :dashboard do
      get '/' => :index
      post '/logout' => :logout
    end
    resources :intentions
    resources :students do
      resources :contact_logs
      member do
        get 'set_to_me' => :set_to_me
      end
      collection do
        post 'query' => :query
      end
    end
  end

end

app/controllers/welcome_controller.rb
# encoding: UTF-8
class WelcomeController < PcApplicationController
  require 'phone_ext'
  before_action :authenticate_user!, only: [:index, :map, :temp, :unsigned]
  def index
  # prepare data for carve display
    start = Date.today.ago(2.month).to_date
    finish = Date.today
    @dates = []
    @signed_up_datas = []
    @signed_up_data_sum = []
    @student_contact_logs = []
    signed_count_total = 0
    while(start < finish) do
      start += 1.day
      # 当前报名人数
      signed_count = Student.where(signed_at: start).count
      # 累计报名人数
      signed_count_total += signed_count
      # 插入时间轴数据
      @dates << start.strftime("%m-%d")
      # 插入每天报名数据
      @signed_up_datas << signed_count
      # 插入累计到每天的报名数据
      @signed_up_data_sum << signed_count_total
      # 插入每天的联系记录数据
      @student_contact_logs << ContactLog.where("date(created_at) = ?", start).count
    end
    # for message display
    @messages = colleact_messages
    @students = Student.joins(:intention).where(intentions: {current_status: 4}).order(signed_at: :desc)
    @stu_wait = @students.where(process: 0)
    @stu_km1 = @students.where(process: 1)
    @stu_km2 = @students.where(process: 2)
    @stu_km3 = @students.where(process: 3)
    @stu_km4 = @students.where(process: 4)
    @stu_lz = @students.where(process: 5)
    # pays
    @fees = Fee.joins(:student).where(students: { identity: 0}).where(fees: { fee_mode: 1 }).where("fees.amount > fees.total_paid")
  end

  def demo
  end

  def map
    @train_fields = TrainField.all
    @schools = School.where("longitude is not null and latitude is not null")
    @average_longitude = TrainField.average(:longitude).to_f
    @average_latitude = TrainField.average(:latitude).to_f
  end

  def temp
    # 显示校园
    @schools = School.all
  end

  def unsigned
    @students = Student.joins(:intention).where(intentions: {current_status: 0..3}).order(created_at: :asc)
  end

  private

  def colleact_messages
    messages = []
    messages += birthday_messages
    messages += book_km1_messages
  end

  def birthday_messages
    messages = []
    Student.where("birthday is not null and signed_at is not null").each do |student|
      days_before_birthday = student.birthday.days_before_birthday
      messages << "<a target='_blank' href='/students/#{student.id}'>#{student.name}</a> #{days_before_birthday} 天后过生日" if days_before_birthday < 10
    end
    messages
  end

  def book_km1_messages
    messages = []
    Student.where(km1_status: Student.km1_statuses['need_order']).each do |student|
      messages << "<a target='_blank' href='/students/#{student.id}'>#{student.name}</a> 可以预约科目一"
    end
    messages
  end

end

app/views/welcome/_fee_list.html.erb
<style type="text/css">
  span.slow {
    padding: 2px;
    background-color: coral;
    color: white;
    border-radius: 6px;
    margin-left: 3px;
  }
  span.unlocked {
    padding: 2px;
    background-color: red;
    color: white;
    border-radius: 6px;
    margin-left: 3px;
  }
  span.trained {
    padding: 2px;
    background-color: red;
    color: white;
    border-radius: 6px;
    margin-left: 3px;
  }
  span.unlocked.done, span.trained.done {
    background-color: green;
  }
</style>

<table class="ui fixed single line selectable teal sortable celled table">
  <thead>
    <tr>
      <th data-width="2" class="two wide">姓名</th>
      <th data-width="2" class="two wide center aligned">出入</th>
      <th data-width="2" class="two wide center aligned">类别</th>
      <th data-width="4" class="four wide aligned">费用说明</th>
      <th data-width="2" class="two wide right aligned" data-sort="num">金额</th>
      <th data-width="4" class="four wide center aligned">状态</th>
    </tr>
  </thead>
  <tbody>
    <% @fees.each do |fee| %>
    <%
      if fee.total_paid == fee.amount
        fee_rate = 100
      else
        fee_rate = fee.total_paid * 100 / fee.amount
      end
    %>
    <tr class="<%= fee.student.intention.current_status %>">
      <!-- 姓名 -->
      <% if fee.student.id_card.present? %>
      <td class="middle aligned" title="<%= fee.student.name %>">
          <%= link_to fee.student.name, student_path(fee.student), target: '_blank' %>
      </td>
      <% else %>
      <td class="middle aligned" style="color: red;" title="<%= fee.student.name %>">
        <%= link_to fee.student.name, student_path(fee.student), target: '_blank' %>
      </td>
      <% end %>
      <!-- 出入 -->
      <td class="middle center aligned">
        <% if fee.shouru? %>
        <i class="add icon" style="color: green;"></i>
        <% else %>
        <i class="minus icon" style="color: red;"></i>
        <% end %>
      </td>
      <!-- 类别 -->
      <td class="middle center aligned" title="<%= fee.fee_type_name %>">
        <%= fee.fee_type_name %>
      </td>
      <!-- 备注 -->
      <td class="middle aligned" title="<%= fee.remark %>">
        <%= fee.remark %>
      </td>
      <td class="middle right aligned" title="<%= number_to_currency(fee.amount, precision: 2, unit: '') %>">
        <%= number_to_currency(fee.amount, precision: 2, unit: '') %>
      </td>
      <td class="middle center aligned">
        <div class="prog-container">
          <div class="prog-text<%= ' warning' if !(0..100).include?(fee_rate) %>">
            <% if fee.amount == fee.total_paid %>
            100%
            <% else %>
            <%= "#{number_to_currency(fee_rate, precision: 2, unit: '')}%" %>
            <% end %>
          </div>
          <div class="prog-bar<%= ' warning' if !(0..100).include?(fee_rate) %>" style="width: <%= fee_rate > 100 ? '100' : fee_rate.round(0) %>%;">
          </div>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">
  $('table').tablesort();
</script>

app/views/welcome/demo.html.erb
<% content_for :title, "Demo" %>
<div>
  <button class="ui button">
    Button
  </button>
  <div class="ui secondary button" tabindex="0">
    1
  </div>
  <div class="ui button">
    2
  </div>
  <div class="ui animated button" tabindex="0">
    <div class="visible content">Next</div>
    <div class="hidden content">
      <i class="right icon arrow"></i>
    </div>
  </div>
  <div class="ui labeled button" tabindex="0">
    <div class="ui red button">
      <i class="heart icon"></i> Like
    </div>
    <a class="ui basic red left pointing label">
      1,048
    </a>
  </div>
  <button class="ui labeled icon button">
    <i class="pause icon"></i>1
  </button>
  <div class="ui segment">
    <button class="ui green basic button">Basic Green</button>
  </div>
  <div class="ui buttons">
    <button class="ui button">One</button>
    <button class="ui button">Two</button>
    <button class="ui button">Three</button>
  </div>
  <div class="ui buttons">
    <button class="ui button active">Cancel</button>
    <div class="or"></div>
    <button class="ui positive button">Save</button>
  </div>
  <button class="ui facebook button">
    <i class="facebook icon"></i>
    脸书
  </button>
  <button class="ui right floated button">Right Floated</button>
</div>
<div>1</div>
<div>
  <button class="ui button">
    Hold
  </button>
  <button class="ui icon button">
    <i class="pause icon"></i>
  </button>
  <button class="ui labeled icon button">
    <i class="pause icon"></i>
    Pause
  </button>
</div>
<div>3</div>

<div>1</div>
<div style="position: relative;width: 800px;margin-left: 20px;">
  <div class="ui two column middle aligned very relaxed stackable grid">
    <div class="column">
      <div class="ui form">
        <div class="field">
          <label>Username</label>
          <div class="ui left icon input">
            <i class="user icon"></i>
            <input placeholder="Username" type="text">
          </div>
        </div>
        <div class="field">
          <label>Password</label>
          <div class="ui left icon input">
            <i class="lock icon"></i>
            <input type="password" placeholder="pass word" />
          </div>
        </div>
        <div class="ui blue submit button">Login</div>
      </div>
    </div>
    <div class="ui vertical divider">
      Or
    </div>
    <div class="center aligned column">
      <div class="ui big green labeled icon button">
        <i class="signup icon"></i>
        Sign Up
      </div>
    </div>
  </div>
</div>
<div>
  <h4 class="ui horizontal divider header">
    <i class="icon tag"></i>
    Description
  </h4>
</div>
<div>
  <div class="ui segment">
    Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.
    <div class="ui fitted divider"></div>
    Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.
  </div>
</div>
<div class="ui segment">
  <h2 class="ui right floated header">Floated Content</h2>
  <div class="ui clearing divider"></div>
  <p>hgdjfjhfjilyvkjgk</p>
</div>
<table class="ui celled table">
  <thead>
    <tr><th>Header</th>
    <th>Header</th>
    <th>Header</th>
  </tr></thead>
  <tbody>
    <tr>
      <td>
        <div class="ui ribbon label">First11111</div>
      </td>
      <td>Cell</td>
      <td>Cell</td>
    </tr>
    <tr>
      <td>Cell</td>
      <td>Cell</td>
      <td>Cell</td>
    </tr>
    <tr>
      <td>Cell</td>
      <td>Cell</td>
      <td>Cell</td>
    </tr>
  </tbody>
  <tfoot>
    <tr><th colspan="3">
      <div class="ui right floated pagination menu">
        <a class="icon item">
          <i class="left chevron icon"></i>
        </a>
        <a class="item">1</a>
        <a class="item">2</a>
        <a class="item">3</a>
        <a class="item">4</a>
        <a class="icon item">
          <i class="right chevron icon"></i>
        </a>
      </div>
    </th>
  </tr></tfoot>
</table>

<i class="chevron down icon"></i>
<div style="width: 100%">
  <table class="ui teal striped sortable celled table">
    <thead>
      <tr>
        <th class="five wide">Name</th>
        <th class="five wide">Status</th>
        <th class="six wide sorted ascending">Notes</th>
      </tr>
    </thead>
    <tbody>
      <tr>
          <td class="middle aligned">Jill</td>
          <td class="middle aligned">Denied</td>
          <td class="middle aligned">None</td>
      </tr>
      <tr>
          <td class="middle aligned">John</td>
          <td class="middle aligned">No Action</td>
          <td class="middle aligned">None</td>
      </tr>
      <tr>
        <td>Jamie</td>
        <td class="middle aligned positive">Approved</td>
        <td class="middle aligned warning">Requires call</td>
      </tr>
    </tbody>
  </table>
</div>


<script type="text/javascript">
  $('table').tablesort();
</script>

app/views/welcome/index.html.erb
<script src="/javascripts/echarts.min.js"></script>
<% content_for :title, "极速学车ERP系统" %>
<% if flash[:alert].present? %>
  <div class="ui error message" style="display:block;">
    <%= flash[:alert] %>
  </div>
<% end %>
<div class="welcome">
  <div class="ui grid">
    <div class="ui row">
      <div class="six wide column" style="padding-top: 0;">
        <div class="ui raised text segment" style="margin-top: 10px;">
          <h2 class="ui header">新的意向</h2>
          <p>当我们得到了意向学员的联系方式后，我们就需要来这里录入我们的意向，避免浪费。</p>
          <%= link_to new_intention_path do %>
            <div class="ui primary labeled icon button">
              添加意向
              <i class="add icon"></i>
            </div>
          <% end %>
          <%= link_to '意向墙', intentions_path, class: 'ui primary button' %>
        </div>
      </div>
      <div class="ten wide column" style="padding-top: 0;">
        <div class="ui raised text segment" style="margin-top: 10px;margin-top: 10px;height: 300px;overflow-y: scroll;">
          <div class="ui header thin">待支付费用</div>
          <div class="ui divider thin"></div>
          <% if current_user.has_role?(:superadmin) || current_user.has_role?(:user) %>
          <%= render 'fee_list' %>
          <% else %>
          无权限
          <% end %>
        </div>
      </div>
    </div>
    <div class="ui row">
      <div class="four wide column">
        <div class="ui raised text segment">
          <div class="ui header thin">进度慢的学员</div>
          <div class="ui divider thin"></div>
          <div class="ui list">
            <% Student.signed.where(is_slow: true).each do |stu| %>
            <div class="item">
              <i class="mail icon"></i>
              <div class="content">
                <%= link_to "#{stu.name}", student_path(stu), { target: '_blank', style: 'width: 60px;display: inline-block;' } %>（<%= PhoneExt.format_phone(stu.phone) %>）
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="four wide column">
        <div class="ui raised text segment">
          <div class="ui header thin">居住证领取</div>
          <div class="ui divider thin"></div>
          <div class="ui list">
            <% ResidenceCard.have_card.each do |residence_card| %>
            <div class="item">
              <i class="mail icon"></i>
              <div class="content">
                <%= link_to "#{residence_card.name}", student_path(residence_card.student), { target: '_blank', style: 'width: 60px;display: inline-block;' } %>（<%= PhoneExt.format_phone(residence_card.student.phone) %>）
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="four wide column">
        <div class="ui raised text segment">
          <div class="ui header thin">签到详情</div>
          <div class="ui divider thin"></div>
          <div class="ui list">
            <% User.normal.each do |user| %>
            <div class="item">
              <i class="mail icon"></i>
              <div class="content">
                <span style="width: 100px;display: inline-block;"><%= user.name %></span>
                <% if user.daily_signs.where("daily_signs.created_at >= ?", Time.zone.now.beginning_of_day).count > 0 %>
                <span style="padding: 0.3em 0.5em;color: blue;">已签到</span>
                <% else %>
                <span style="padding: 0.3em 0.5em;color: red;">未签到</span>
                <% end %>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="four wide column">
        <div class="ui raised text segment">
          <div class="ui header thin">消息墙</div>
          <div class="ui divider thin"></div>
          <div class="ui list">
            <% @messages.each do |message| %>
            <div class="item">
              <i class="mail icon"></i>
              <div class="content">
                <%= message.html_safe %>
              </div>
            </div>
            <% end if @messages.present? %>
          </div>
        </div>
      </div>
    </div>
    <div class="ui row">
      <div class="four wide column">
        <div class="ui raised text segment">
          <div class="ui header thin">已报名无教练或服务</div>
          <div class="ui divider thin"></div>
          <div class="ui list">
            <% Student.where("signed_at is not null and (coach_id is null or train_service_id is null)").each do |student| %>
            <div class="item">
              <i class="mail icon"></i>
              <div class="content">
                <%= link_to "#{student.name}", student_path(student), { target: '_blank', style: 'width: 60px;display: inline-block;' } %>（<%= PhoneExt.format_phone(student.phone) %>）
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="twelve wide column">
        <div class="ui raised text segment">
          <div class="ui header thin">需预约学员信息</div>
          <div class="ui divider thin"></div>
          <div class="ui list">
            <% Student.where(km1_status: Student.km1_statuses['need_order']).each do |student| %>
            <div class="item">
              <i class="mail icon"></i>
              <div class="content">
                <%= "#{student.name} #{student.id_card}" %>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% if current_user.has_role?(:superadmin) || current_user.has_role?(:user) %>
    <div class="ui row">
      <div class="sixteen wide column">
        <div id="chartStudentDist" style="width: 100%;height: 500px;"></div>
      </div>
      <div class="eight wide column">
      </div>
    </div>
    <div class="ui row">
      <div class="eight wide column">
        <div id="chartSigned" style="width: 100%;height: 300px;"></div>
      </div>
      <div class="eight wide column">
        <div id="chartStudentContact" style="width: 100%;height: 300px;"></div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<% if current_user.has_role?(:superadmin) || current_user.has_role?(:user) %>
<script type="text/javascript">
  (function() {
    var signedUpChart = echarts.init($('#chartSigned')[0]);
    var studentContactLogChart = echarts.init($('#chartStudentContact')[0])
    var studentDistChart = echarts.init($('#chartStudentDist')[0]);

    var signedUpOption = {
      title: {
        text: '报名趋势图'
      },
      tooltip: {
        trigger: 'axis'
      },
      legend: {
        data: ['当日报名', '累计报名', '联系学员']
      },
      grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
      },
      toolbox: {
        feature: {
          saveAsImage: {}
        }
      },
      xAxis: [{
        type: 'category',
        boundaryGap: false,
        data: <%= @dates.to_json.html_safe %>
      }],
      yAxis: [{
        type: 'value'
      }],
      dataZoom: {
        type: 'inside'
      },
      series: [{
        name: '当日报名',
        type: 'line',
        smooth: true,
        data: <%= @signed_up_datas.to_json.html_safe %>
      },{
        name: '累计报名',
        type: 'line',
        smooth: true,
        data: <%= @signed_up_data_sum.to_json.html_safe %>
      },{
        name: '联系学员',
        type: 'line',
        smooth: true,
        data: <%= @student_contact_logs.to_json.html_safe %>
      }]
    };
    var studentContactLogOption = {
      title: {
        text: '学员联系趋势图'
      },
      tooltip: {
        trigger: 'axis'
      },
      legend: {
        data: ['当日联系']
      },
      grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
      },
      toolbox: {
        feature: {
          saveAsImage: {}
        }
      },
      xAxis: [{
        type: 'category',
        boundaryGap: false,
        data: <%= @dates.to_json.html_safe %>
      }],
      yAxis: [{
        type: 'value'
      }],
      dataZoom: {
        type: 'inside'
      },
      series: [{
        name: '当日联系',
        type: 'line',
        smooth: true,
        data: <%= @student_contact_logs.to_json.html_safe %>
      }]
    };
    var studentDistChartOption = {
      title : {
        text: '极速学车学员分布表',
        subtext: '<%= Date.today.to_s(:db) %>',
        x:'center'
      },
      tooltip : {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
      },
      legend: {
        orient: 'vertical',
        left: 'left',
        data: ['等待','科一','科二','科三','科四','已拿证']
      },
      series : [
      {
        name: '访问来源',
        type: 'pie',
        radius : '55%',
        center: ['50%', '60%'],
        data:[
        {value:<%= @stu_wait.count %>, name:'等待'},
        {value:<%= @stu_km1.count %>, name:'科一'},
        {value:<%= @stu_km2.count %>, name:'科二'},
        {value:<%= @stu_km3.count %>, name:'科三'},
        {value:<%= @stu_km4.count %>, name:'科四'},
        {value:<%= @stu_lz.count %>, name:'已拿证'}
        ],
        itemStyle: {
          emphasis: {
            shadowBlur: 10,
            shadowOffsetX: 0,
            shadowColor: 'rgba(0, 0, 0, 0.5)'
          }
        }
      }
      ]
    };

    signedUpChart.setOption(signedUpOption);
    studentContactLogChart.setOption(studentContactLogOption);
    studentDistChart.setOption(studentDistChartOption);
  })();
</script>
<% end %>

app/views/welcome/unsigned.html.erb
<% content_for :title, "未报名学员 - 极速学车ERP系统" %>
<div class="ui segment coach">
  <table class="ui teal striped sortable celled table">
    <thead>
      <tr>
        <th class="one wide">序号</th>
        <th class="three">姓名</th>
        <th class="four wide">手机</th>
        <th class="eight wide">意向评估</th>
      </tr>
    </thead>
    <tbody>
      <% @students.each_with_index do |student, index| %>
      <tr>
        <td class="middle center aligned"><%= (index + 1).to_s.rjust(3, '0') %></td>
        <td class="middle"><%= link_to "#{student.name}", intention_path(student.intention), { target: '_blank' } %></td>
        <td class="middle aligned text"><%= PhoneExt.format_phone(student.phone) %></td>
        <td class="middle aligned text">
          <textarea data-type="evaluation" data-student-id="<%= student.id %>" style="height: 150px;width: 100%;"><%= student.evaluation %></textarea>
          <button class="ui primary button save-evaluation">更新</button>
          <span style="color: red;" class="msg-warning"></span>
          <span style="color: green;" class="msg-success"></span>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<script type="text/javascript">
  var __sto = setTimeout;　　
  window.setTimeout = function(callback, timeout, param)　　 {　　
    var args = Array.prototype.slice.call(arguments, 2);　　
    var _cb = function()　　 {　　
      callback.apply(null, args);　　
    }　　
    __sto(_cb, timeout);　　
  }
</script>
<script type="text/javascript">
  function update(id, evaluation, jq_td, showConfirm) {
    if (showConfirm && !confirm('是否更新？')) {
      return;
    }
    $.post('/students/update_evaluation', {
      'id': id,
      'evaluation': evaluation
    }).success(function(data) {
      if (data && data.msg_code == 'success') {
        jq_td.find('.msg-success').html('更新成功！');
        setTimeout(function(td) {
          td.find('.msg-success').html('');
        }, 1500, jq_td);
      } else {
        jq_td.find('.msg-warning').html('更新错误，请联系管理员！');
        setTimeout(function(td) {
          td.find('.msg-warning').html('');
        }, 1500, jq_td);
      }
    }).error(function(data) {
        jq_td.find('.msg-warning').html('更新错误，请联系管理员！');
        setTimeout(function(td) {
          td.find('.msg-warning').html('');
        }, 1500, jq_td);
    });
  }

  function valid(id, evaluation, jq_td) {
    $.post('/students/peek_before_evaluation', {
      'id': id
    }).success(function(data) {
      if (data && data.msg_code == 'success') {
        update(id, evaluation, jq_td, true);
      } else {
        if (data && data.msg_code == 'error') {
          if (confirm(data.msg_text)) {
            update(id, evaluation, jq_td, false);
          }
        } else {
          jq_td.find('.msg-warning').html('校验错误！');
          setTimeout(function(td) {
            td.find('.msg-warning').html('');
          }, 1500, jq_td);
        }
      }
    }).error(function(data) {
        jq_td.find('.msg-warning').html('校验错误！');
        setTimeout(function(td) {
          td.find('.msg-warning').html('');
        }, 1500, jq_td);
    });
  }
</script>
<script type="text/javascript">
  $('table').tablesort();
  $('.save-evaluation').on('click', function() {
    var jq_td = $(this.parentNode);
    var textarea = $('textarea', this.parentNode);
    var student_id = textarea.attr('data-student-id');
    var evaluation_text = textarea.val();

    valid(student_id, evaluation_text, jq_td);
  });
</script>